# Generated by Django 5.1 on 2025-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_contenido', models.IntegerField()),
                ('tipo_contenido', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
